# Generated by Django 4.2.11 on 2024-04-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('encoded_img', models.ImageField(upload_to='encoded_images/')),
            ],
        ),
        migrations.AddField(
            model_name='img',
            name='secret_msg',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
    ]
