# Generated by Django 4.2.11 on 2024-04-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0002_encodedimg_img_secret_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='name',
        ),
    ]
