# Generated by Django 4.2.11 on 2024-04-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgtodecode',
            name='img',
            field=models.ImageField(upload_to='images_to_decode/'),
        ),
        migrations.AlterField(
            model_name='secretmessage',
            name='secret_img',
            field=models.ImageField(upload_to='decoded_images/'),
        ),
    ]
